config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # error
  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home


    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])

    end
    @users_in_db = User.where(activated: true).count

    my_log "PRUEBA"

    # system("    curl -s --user 'api:key-401c0b6ce947507697901c3d460b2c99' \
    # https://api.mailgun.net/v3/sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org/messages \
    # -F from='PUTOOOO <postmaster@sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org>' \
    # -F to='juanca <juanxstingo@gmail.com>' \
    # -F subject='Hello juanca' \
    # -F text='Congratulations juanca, you just sent an email with Mailgun!  You are truly awesome!' ")

    #Rails.logger.debug "\033[1;34;40m[DEBUG] Juanca-DEBUG: \033[0m " + output
  end

  def help

    texto = Time.zone.now
    my_log texto.to_s

    current_user.create_reset_digest
    current_user.send_password_reset_email

    # output = `curl -s --user 'api:key-401c0b6ce947507697901c3d460b2c99' \
    #  https://api.mailgun.net/v3/sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org/messages \
    #  -F from='Rama <postmaster@sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org>' \
    #  -F to='juanca <juanxstingo@gmail.com>' \
    #  -F subject='asunto' \
    #  -F text='cuerpo del mensaje'`

    #Rails.logger.debug "\033[1;34;40m[DEBUG] Juanca-DEBUG: \033[0m " + output

    # system("    curl -s --user 'api:key-401c0b6ce947507697901c3d460b2c99' \
    # https://api.mailgun.net/v3/sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org/messages \
    # -F from='PUTOOOO <postmaster@sandboxd49dad5e176b4884aede3fdb9b1bac75.mailgun.org>' \
    # -F to='juanca <juanxstingo@gmail.com>' \
    # -F subject='Hello juanca' \
    # -F text='Congratulations juanca, you just sent an email with Mailgun!  You are truly awesome!' ")
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_logged_in.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_home_not_logged_in.html.erb
<div class="center jumbotron">
<h1>Welcome to Juanca App</h1>
  <h2>
    juanca app! <a href="http://cv.stingo.com.ar">my page</a>
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  My fist page. about tu mama
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  <%= mail_to "stingo@stingo.com.ar", "My email address", cc: "no-one@no-where.com",
         subject: "te regalo unos pesitos" %> 
  
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

    <h1>Help</h1>
      <p>Help yourself!</p>

app/views/static_pages/home.html.erb
<center>
  <h3> <%= link_to "Users: #{@users_in_db}", users_path  %> </h3>
</center>

<% if logged_in? %>
  <%= render 'home_logged_in' %>
<% else %>
<div class="center jumbotron">
  <%= render 'home_not_logged_in' %>
<% end %>